# fly.toml file generated for value-selling-tracker on 2023-06-01T13:12:52-05:00

app = "value-selling-tracker"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "atl"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
