GET http://localhost:3001/api/opps

###
POST http://localhost:3001/api/opps
Content-Type: application/json

{
 "company": "React",
 "contact": "Tech Lord",
 "businessIssue": "bored",
 "anxietyQ": "What are you gonna do when they come for you?",
 "problem": "Too tired",
 "solution": "sleep",
 "value": "rest is good",
 "power": "jeff",
 "plan": "sell"
} 

###
DELETE http://localhost:3001/api/opps/6459bb87a0bb9f1ebe50d54e